-- MySQL Script generated by MySQL Workbench
-- 02/25/15 11:09:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EmpresaDeMontaje
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EmpresaDeMontaje` ;
CREATE SCHEMA IF NOT EXISTS `EmpresaDeMontaje` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `EmpresaDeMontaje` ;

-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`Componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`Componentes` (
  `idComponentes` BIGINT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `Stock` INT NOT NULL,
  `StockMinimo` INT NOT NULL,
  `PrecioComponente` DOUBLE NOT NULL,
  PRIMARY KEY (`idComponentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`Clientes` (
  `idClientes` BIGINT NOT NULL AUTO_INCREMENT,
  `Dni` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `TelefonoFijo` VARCHAR(9) NULL,
  `TelefonoMovil` VARCHAR(9) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `CorreoElectronico` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Dni_UNIQUE` ON `EmpresaDeMontaje`.`Clientes` (`Dni` ASC);

CREATE UNIQUE INDEX `idClientes_UNIQUE` ON `EmpresaDeMontaje`.`Clientes` (`idClientes` ASC);


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`Productos` (
  `idProductos` BIGINT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `PrecioProducto` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`Proveedores` (
  `idProveedor` BIGINT NOT NULL AUTO_INCREMENT,
  `NombreProveedor` VARCHAR(45) NOT NULL,
  `TelefonoProveedor` VARCHAR(9) NULL,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `TelefonoEmpresa` VARCHAR(9) NOT NULL,
  `DireccionEmpresa` VARCHAR(100) NOT NULL,
  `CorreoElectronicoEmpresa` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`ComponentesDeProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`ComponentesDeProducto` (
  `Productos_idProductos` BIGINT NOT NULL,
  `Componentes_idComponentes` BIGINT NOT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Componentes_idComponentes`),
  CONSTRAINT `fk_Productos_has_Componentes_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `EmpresaDeMontaje`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Componentes_Componentes1`
    FOREIGN KEY (`Componentes_idComponentes`)
    REFERENCES `EmpresaDeMontaje`.`Componentes` (`idComponentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_has_Componentes_Componentes1_idx` ON `EmpresaDeMontaje`.`ComponentesDeProducto` (`Componentes_idComponentes` ASC);

CREATE INDEX `fk_Productos_has_Componentes_Productos1_idx` ON `EmpresaDeMontaje`.`ComponentesDeProducto` (`Productos_idProductos` ASC);


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`PedidosClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`PedidosClientes` (
  `idPedidosClientes` BIGINT NOT NULL AUTO_INCREMENT,
  `FechaInicioPedido` DATETIME NOT NULL DEFAULT Now(),
  `FechaFinPedido` DATETIME NULL,
  `EstadoPedido` ENUM('Registrado','Montado','Servido') NOT NULL DEFAULT 'Registrado',
  `PrecioTotalPedidoCliente` DOUBLE NOT NULL DEFAULT 0,
  `Clientes_idClientes` BIGINT NOT NULL,
  PRIMARY KEY (`idPedidosClientes`),
  CONSTRAINT `fk_Pedidos_Clientes10`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `EmpresaDeMontaje`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedidos_Clientes1_idx` ON `EmpresaDeMontaje`.`PedidosClientes` (`Clientes_idClientes` ASC);


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`PedidosProveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`PedidosProveedores` (
  `idPedidosProveedores` BIGINT NOT NULL AUTO_INCREMENT,
  `FechaPedido` DATETIME NOT NULL DEFAULT Now(),
  `PrecioTotalPedidoProveedor` DOUBLE NOT NULL DEFAULT 0,
  `Proveedores_idProveedor` BIGINT NOT NULL,
  PRIMARY KEY (`idPedidosProveedores`),
  CONSTRAINT `fk_PedidosProveedores_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `EmpresaDeMontaje`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PedidosProveedores_Proveedores1_idx` ON `EmpresaDeMontaje`.`PedidosProveedores` (`Proveedores_idProveedor` ASC);


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`LineasDePedidoClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`LineasDePedidoClientes` (
  `idLineasDePedidoClientes` BIGINT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `Terminado` TINYINT(1) NOT NULL DEFAULT 0,
  `PedidosClientes_idPedidosClientes` BIGINT NOT NULL,
  `Productos_idProductos` BIGINT NOT NULL,
  PRIMARY KEY (`idLineasDePedidoClientes`, `PedidosClientes_idPedidosClientes`, `Productos_idProductos`),
  CONSTRAINT `fk_Productos_has_PedidosClientes_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `EmpresaDeMontaje`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_PedidosClientes_PedidosClientes1`
    FOREIGN KEY (`PedidosClientes_idPedidosClientes`)
    REFERENCES `EmpresaDeMontaje`.`PedidosClientes` (`idPedidosClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_has_PedidosClientes_PedidosClientes1_idx` ON `EmpresaDeMontaje`.`LineasDePedidoClientes` (`PedidosClientes_idPedidosClientes` ASC);

CREATE INDEX `fk_Productos_has_PedidosClientes_Productos1_idx` ON `EmpresaDeMontaje`.`LineasDePedidoClientes` (`Productos_idProductos` ASC);


-- -----------------------------------------------------
-- Table `EmpresaDeMontaje`.`LineasDePedidoProveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaDeMontaje`.`LineasDePedidoProveedores` (
  `idLineasDePedidoProveedores` BIGINT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `Componentes_idComponentes` BIGINT NOT NULL,
  `PedidosProveedores_idPedidosProveedores` BIGINT NOT NULL,
  PRIMARY KEY (`idLineasDePedidoProveedores`, `Componentes_idComponentes`, `PedidosProveedores_idPedidosProveedores`),
  CONSTRAINT `fk_Componentes_has_PedidosProveedores_Componentes1`
    FOREIGN KEY (`Componentes_idComponentes`)
    REFERENCES `EmpresaDeMontaje`.`Componentes` (`idComponentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Componentes_has_PedidosProveedores_PedidosProveedores1`
    FOREIGN KEY (`PedidosProveedores_idPedidosProveedores`)
    REFERENCES `EmpresaDeMontaje`.`PedidosProveedores` (`idPedidosProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Componentes_has_PedidosProveedores_PedidosProveedores1_idx` ON `EmpresaDeMontaje`.`LineasDePedidoProveedores` (`PedidosProveedores_idPedidosProveedores` ASC);

CREATE INDEX `fk_Componentes_has_PedidosProveedores_Componentes1_idx` ON `EmpresaDeMontaje`.`LineasDePedidoProveedores` (`Componentes_idComponentes` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
